title: SSoulSS
description: >
  Software product development for healthcare and booking systems.
tagline: "Technology with a Soul"
baseurl: ""
url: "https://pauljos.github.io/ssoulss" # temporary â€” update after repo setup
theme: "minimal-mistakes-jekyll"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# minimal mistakes settings (keep defaults for now)
markdown: kramdown
highlighter: rouge

# where to place assets
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
